language: python
python:
  - "2.7"
env:
  - SKADI='basic'
  - SKADI='cython'
install:
  - sudo apt-get install libsnappy1 libsnappy-dev libprotobuf7 libprotoc7 protobuf-compiler
  - pip install bitstring==3.1.2 python-snappy==0.5 protobuf==2.5 cython==0.19.1
  - git clone https://github.com/skadistats/skadi.git
  - pushd skadi
  - bash -c "if [[ $SKADI == 'basic' ]]; then python setup_basic.py install; fi"
  - bash -c "if [[ $SKADI == 'cython' ]]; then python setup.py install; fi"
  - popd
script: nosetests